# Generated by Django 3.2 on 2021-05-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_lectures', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
